Fix for LDEV-3008: Upload new extension UI Asks for Wrong File Type.
lucee/Lucee pull request #1002
Opened 2020-08-13 20:52 UTC by JayIsPainting

Changed 3 language files to modify UI from asking for ZIP files when expecting LEX files.

2020-08-13 20:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/lucee/Lucee?pullRequest=1002) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/lucee/Lucee?pullRequest=1002) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/lucee/Lucee?pullRequest=1002) it.</sub>

2020-08-13 20:56 UTC, zspitzer requested changes
File shouldn't be upper case?

2020-08-13 21:01 UTC, JayIsPainting commented
I tend to do that for input labels but I can certainly change it.

2022-01-17 10:54 UTC, michaeloffner commented
manually adapted the change because of merge conflicts
https://github.com/lucee/Lucee/commit/372cc048da2710a0067f649829107ceba19fbc8d

2022-01-17 10:54 UTC, closed without merging