Added a test case and fix for LDEV-2902
lucee/Lucee pull request #1070
Opened 2020-10-13 15:41 UTC by cfmitrah

2020-12-15 07:47 UTC, jbampton requested changes

2020-12-15 07:47 UTC, jbampton commented on test/tickets/LDEV2902/Application.cfc
> +	msSQL = getCredencials();
```suggestion
	msSQL = getCredentials();
```

2020-12-15 07:47 UTC, jbampton commented on test/tickets/LDEV2902/Application.cfc
> +	private struct function getCredencials() {
```suggestion
	private struct function getCredentials() {
```

2020-12-15 07:47 UTC, jbampton commented on test/tickets/LDEV2902/Application.cfc
> +		// getting the credetials from the enviroment variables
```suggestion
		// getting the credentials from the environment variables
```

2020-12-15 07:47 UTC, jbampton commented on test/tickets/LDEV2902/Application.cfc
> +		// getting the credetials from the system variables
```suggestion
		// getting the credentials from the system variables
```

2020-12-15 07:47 UTC, jbampton commented on test/tickets/LDEV2902/test.cfm
> +
```suggestion
```

2021-11-19 15:06 UTC, michaeloffner commented
manually adapted the PR

2021-11-19 15:06 UTC, closed without merging