Resolved the conflicts and added "epochms" mask
lucee/Lucee pull request #1233
Opened 2021-03-16 13:50 UTC by cfmitrah

https://luceeserver.atlassian.net/browse/LDEV-2439

2021-03-31 21:25 UTC, zspitzer commented
can add you add epochms to the documentation?

2021-04-01 15:09 UTC, cfmitrah commented
@zspitzer done in (https://github.com/lucee/lucee-docs/pull/1097)

2021-04-04 14:45 UTC, zspitzer commented
I meant in the .fld file in this PR :)

2021-04-04 14:45 UTC, zspitzer requested changes

2021-04-04 14:45 UTC, zspitzer commented on core/src/main/java/resource/fld/core-cfml.fld
> +- epoch: Total seconds of a given date (Example:1567517664)
epochms is missing

2021-04-07 06:27 UTC, cfmitrah commented on core/src/main/java/resource/fld/core-cfml.fld
> +- epoch: Total seconds of a given date (Example:1567517664)
Added that too.

2021-04-07 09:39 UTC, merged