Added a fix to improve the error message for LDEV-3383
lucee/Lucee pull request #1242
Opened 2021-03-23 07:25 UTC by cfmitrah

https://luceeserver.atlassian.net/browse/LDEV-3383

2021-04-07 14:32 UTC, zspitzer requested changes

2021-04-07 14:32 UTC, zspitzer commented on core/src/main/java/lucee/commons/lang/ExceptionUtil.java
> +				return "The " + keyLabel + " [" + keySearched + "] does not exist" + inThe + ", but there is a similar " + keyLabel + " with name [" + _keys[i].getString()
`_keys[i].getString()` should be list?

2021-04-07 14:32 UTC, zspitzer commented on core/src/main/java/lucee/runtime/type/util/MemberUtil.java
> +		String detail = ExceptionUtil.similarKeyMessage(keys.toArray(new Key[keys.size()]), methodName.getString(), "functions",
the detail is the same as the message?

2021-04-07 14:32 UTC, zspitzer commented on core/src/main/java/lucee/runtime/type/util/StructSupport.java
> +		if (config != null && config.debug()) return new ExpressionException(msg+ " " +detail);
shouldn't this be `ExpressionException(msg, detail);` ?

2021-04-07 14:32 UTC, zspitzer commented on core/src/main/java/lucee/runtime/type/BIF.java
> +			throw new ApplicationException(msg+ " " +detail);
`ApplicationException(msg, detail);` ?

2021-04-07 14:32 UTC, zspitzer commented on core/src/main/java/lucee/runtime/tag/Log.java
> +					throw new ApplicationException(msg+ " " +detail);
`ApplicationException(msg, detail);` ?

2021-04-16 11:34 UTC, cfmitrah commented on core/src/main/java/lucee/runtime/type/util/MemberUtil.java
> +		String detail = ExceptionUtil.similarKeyMessage(keys.toArray(new Key[keys.size()]), methodName.getString(), "functions",
No, They are diff. I split the similarKeyMessage for msg and details. Call similarKeyMessage() with diff number of arguments to get meg and details.

2021-04-16 12:06 UTC, cfmitrah commented on core/src/main/java/lucee/commons/lang/ExceptionUtil.java
> +				return "The " + keyLabel + " [" + keySearched + "] does not exist" + inThe + ", but there is a similar " + keyLabel + " with name [" + _keys[i].getString()
Not a list. It's a similar function

2022-07-17 16:02 UTC, merged